"""add_milestone7_audit_fields

Revision ID: 166e340a91c7
Revises: ae11da13977c
Create Date: 2026-09-04 02:56:49.866547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166e340a91c7'
down_revision: Union[str, Sequence[str], None] = 'ae11da13977c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('event_status', sa.String(length=32), server_default='succeeded', nullable=False))
    op.add_column('audit_events', sa.Column('payment_attempt_id', sa.String(length=36), nullable=True))
    op.add_column('audit_events', sa.Column('product_id', sa.String(length=64), nullable=True))
    op.add_column('audit_events', sa.Column('correlation_id', sa.String(length=64), nullable=True))
    op.add_column('audit_events', sa.Column('parent_event_id', sa.String(length=36), nullable=True))
    op.add_column('audit_events', sa.Column('provider', sa.String(length=32), nullable=True))
    op.add_column('audit_events', sa.Column('model', sa.String(length=64), nullable=True))
    op.add_column('audit_events', sa.Column('request_id', sa.String(length=64), nullable=True))
    op.add_column('audit_events', sa.Column('reason_code', sa.String(length=64), nullable=True))
    op.add_column('audit_events', sa.Column('failure_code', sa.String(length=64), nullable=True))
    op.add_column('audit_events', sa.Column('recovery_action', sa.String(length=64), nullable=True))
    op.add_column('audit_events', sa.Column('idempotency_key', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_status'), 'audit_events', ['event_status'], unique=False)
    op.create_index(op.f('ix_audit_events_idempotency_key'), 'audit_events', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_audit_events_parent_event_id'), 'audit_events', ['parent_event_id'], unique=False)
    op.create_index(op.f('ix_audit_events_payment_attempt_id'), 'audit_events', ['payment_attempt_id'], unique=False)
    op.create_index(op.f('ix_audit_events_product_id'), 'audit_events', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_product_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_payment_attempt_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_parent_event_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_idempotency_key'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_status'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_column('audit_events', 'idempotency_key')
    op.drop_column('audit_events', 'recovery_action')
    op.drop_column('audit_events', 'failure_code')
    op.drop_column('audit_events', 'reason_code')
    op.drop_column('audit_events', 'request_id')
    op.drop_column('audit_events', 'model')
    op.drop_column('audit_events', 'provider')
    op.drop_column('audit_events', 'parent_event_id')
    op.drop_column('audit_events', 'correlation_id')
    op.drop_column('audit_events', 'product_id')
    op.drop_column('audit_events', 'payment_attempt_id')
    op.drop_column('audit_events', 'event_status')
    # ### end Alembic commands ###
