"""create policies and session_policies tables

Revision ID: 420bb33fcd99
Revises: f24bcabf7d86
Create Date: 2026-09-03 03:20:19.551471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420bb33fcd99'
down_revision: Union[str, Sequence[str], None] = 'f24bcabf7d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_single_transaction_paise', sa.BigInteger(), nullable=False),
    sa.Column('max_cart_total_paise', sa.BigInteger(), nullable=False),
    sa.Column('authorization_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_tier'), 'policies', ['tier'], unique=True)
    op.create_table('session_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('policy_tier', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_policies_id'), 'session_policies', ['id'], unique=False)
    op.create_index(op.f('ix_session_policies_session_id'), 'session_policies', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_policies_session_id'), table_name='session_policies')
    op.drop_index(op.f('ix_session_policies_id'), table_name='session_policies')
    op.drop_table('session_policies')
    op.drop_index(op.f('ix_policies_tier'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
