"""create payment and audit tables

Revision ID: ae11da13977c
Revises: 420bb33fcd99
Create Date: 2026-09-03 17:38:19.698447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae11da13977c'
down_revision: Union[str, Sequence[str], None] = '420bb33fcd99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('checkout_id', sa.String(length=36), nullable=True),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_type'), 'audit_events', ['actor_type'], unique=False)
    op.create_index(op.f('ix_audit_events_checkout_id'), 'audit_events', ['checkout_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_audit_events_order_id'), 'audit_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_audit_events_razorpay_order_id'), 'audit_events', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_audit_events_razorpay_payment_id'), 'audit_events', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('ix_audit_events_session_id'), 'audit_events', ['session_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('razorpay_event_id', sa.String(length=64), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_id'), 'webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_events_payload_hash'), 'webhook_events', ['payload_hash'], unique=True)
    op.create_index(op.f('ix_webhook_events_processing_status'), 'webhook_events', ['processing_status'], unique=False)
    op.create_index(op.f('ix_webhook_events_razorpay_event_id'), 'webhook_events', ['razorpay_event_id'], unique=True)
    op.create_table('checkout_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('cart_id', sa.String(length=36), nullable=False),
    sa.Column('subtotal_paise', sa.BigInteger(), nullable=False),
    sa.Column('total_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('policy_tier', sa.String(length=32), nullable=False),
    sa.Column('policy_decision', sa.String(length=32), nullable=False),
    sa.Column('buyer_confirmed', sa.Boolean(), nullable=False),
    sa.Column('buyer_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cart_snapshot', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkout_sessions_cart_id'), 'checkout_sessions', ['cart_id'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_expires_at'), 'checkout_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_id'), 'checkout_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_session_id'), 'checkout_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_status'), 'checkout_sessions', ['status'], unique=False)
    op.create_table('payment_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('checkout_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('receipt', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checkout_id'], ['checkout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_orders_checkout_id'), 'payment_orders', ['checkout_id'], unique=False)
    op.create_index(op.f('ix_payment_orders_id'), 'payment_orders', ['id'], unique=False)
    op.create_index(op.f('ix_payment_orders_razorpay_order_id'), 'payment_orders', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_payment_orders_receipt'), 'payment_orders', ['receipt'], unique=True)
    op.create_index(op.f('ix_payment_orders_session_id'), 'payment_orders', ['session_id'], unique=False)
    op.create_index(op.f('ix_payment_orders_status'), 'payment_orders', ['status'], unique=False)
    op.create_table('payment_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_description', sa.Text(), nullable=True),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['payment_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_attempts_id'), 'payment_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_order_id'), 'payment_attempts', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_razorpay_order_id'), 'payment_attempts', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_razorpay_payment_id'), 'payment_attempts', ['razorpay_payment_id'], unique=True)
    op.create_index(op.f('ix_payment_attempts_status'), 'payment_attempts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_attempts_status'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_razorpay_payment_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_razorpay_order_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_order_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_id'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index(op.f('ix_payment_orders_status'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_session_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_receipt'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_razorpay_order_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_checkout_id'), table_name='payment_orders')
    op.drop_table('payment_orders')
    op.drop_index(op.f('ix_checkout_sessions_status'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_session_id'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_id'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_expires_at'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_cart_id'), table_name='checkout_sessions')
    op.drop_table('checkout_sessions')
    op.drop_index(op.f('ix_webhook_events_razorpay_event_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_processing_status'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_payload_hash'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_audit_events_session_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_razorpay_payment_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_razorpay_order_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_order_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_checkout_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_type'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
