"""add_milestone9_marketplace_tables

Revision ID: b63706ff112b
Revises: 5c1736e5414e
Create Date: 2026-09-04 20:08:09.415125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b63706ff112b'
down_revision: Union[str, Sequence[str], None] = '5c1736e5414e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_fetch_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('request_type', sa.String(length=64), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message_sanitized', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_fetch_logs_correlation_id'), 'marketplace_fetch_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_marketplace_fetch_logs_provider'), 'marketplace_fetch_logs', ['provider'], unique=False)
    op.create_table('marketplace_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_product_id', sa.String(length=64), nullable=False),
    sa.Column('canonical_url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('subcategory', sa.String(length=128), nullable=True),
    sa.Column('original_description', sa.Text(), nullable=True),
    sa.Column('normalized_description', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('product_attributes', sa.JSON(), nullable=False),
    sa.Column('specifications', sa.JSON(), nullable=False),
    sa.Column('source_currency', sa.String(length=3), nullable=False),
    sa.Column('source_price_minor', sa.BigInteger(), nullable=True),
    sa.Column('source_mrp_minor', sa.BigInteger(), nullable=True),
    sa.Column('availability_status', sa.String(length=32), nullable=False),
    sa.Column('source_rating', sa.Float(), nullable=True),
    sa.Column('source_review_count', sa.Integer(), nullable=True),
    sa.Column('seller_name', sa.String(length=255), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_payload_reference', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_product_id', name='uq_provider_product_id')
    )
    op.create_index(op.f('ix_marketplace_products_brand'), 'marketplace_products', ['brand'], unique=False)
    op.create_index(op.f('ix_marketplace_products_category'), 'marketplace_products', ['category'], unique=False)
    op.create_index(op.f('ix_marketplace_products_provider'), 'marketplace_products', ['provider'], unique=False)
    op.create_index(op.f('ix_marketplace_products_provider_product_id'), 'marketplace_products', ['provider_product_id'], unique=False)
    op.create_index('ix_marketplace_provider_product', 'marketplace_products', ['provider', 'provider_product_id'], unique=False)
    op.create_table('marketplace_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_providers_code'), 'marketplace_providers', ['code'], unique=True)
    op.create_table('marketplace_finance_information',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('marketplace_product_id', sa.String(length=36), nullable=False),
    sa.Column('emi_available', sa.Boolean(), nullable=False),
    sa.Column('emi_provider', sa.String(length=128), nullable=True),
    sa.Column('emi_summary', sa.Text(), nullable=True),
    sa.Column('no_cost_emi_available', sa.Boolean(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['marketplace_product_id'], ['marketplace_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_finance_information_marketplace_product_id'), 'marketplace_finance_information', ['marketplace_product_id'], unique=True)
    op.create_table('marketplace_internal_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('marketplace_product_id', sa.String(length=36), nullable=False),
    sa.Column('marketplace_provider', sa.String(length=32), nullable=False),
    sa.Column('internal_product_id', sa.String(length=36), nullable=True),
    sa.Column('mapping_status', sa.String(length=32), nullable=False),
    sa.Column('mapping_confidence', sa.Float(), nullable=False),
    sa.Column('mapped_by', sa.String(length=64), nullable=False),
    sa.Column('mapped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_validation_status', sa.String(length=32), nullable=False),
    sa.Column('inventory_validation_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['internal_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['marketplace_product_id'], ['marketplace_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_internal_mappings_internal_product_id'), 'marketplace_internal_mappings', ['internal_product_id'], unique=False)
    op.create_index(op.f('ix_marketplace_internal_mappings_marketplace_product_id'), 'marketplace_internal_mappings', ['marketplace_product_id'], unique=True)
    op.create_index(op.f('ix_marketplace_internal_mappings_marketplace_provider'), 'marketplace_internal_mappings', ['marketplace_provider'], unique=False)
    op.create_table('marketplace_offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('marketplace_product_id', sa.String(length=36), nullable=False),
    sa.Column('provider_offer_id', sa.String(length=128), nullable=True),
    sa.Column('seller_name', sa.String(length=255), nullable=True),
    sa.Column('offer_title', sa.String(length=255), nullable=False),
    sa.Column('offer_description', sa.Text(), nullable=True),
    sa.Column('price_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('discount_minor', sa.BigInteger(), nullable=True),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.Column('availability', sa.String(length=64), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('raw_offer_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['marketplace_product_id'], ['marketplace_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_offers_marketplace_product_id'), 'marketplace_offers', ['marketplace_product_id'], unique=False)
    op.create_table('marketplace_product_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('marketplace_product_id', sa.String(length=36), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('image_type', sa.String(length=32), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['marketplace_product_id'], ['marketplace_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_product_images_marketplace_product_id'), 'marketplace_product_images', ['marketplace_product_id'], unique=False)
    op.create_table('marketplace_review_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('marketplace_product_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('rating_distribution', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['marketplace_product_id'], ['marketplace_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_review_summaries_marketplace_product_id'), 'marketplace_review_summaries', ['marketplace_product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplace_review_summaries_marketplace_product_id'), table_name='marketplace_review_summaries')
    op.drop_table('marketplace_review_summaries')
    op.drop_index(op.f('ix_marketplace_product_images_marketplace_product_id'), table_name='marketplace_product_images')
    op.drop_table('marketplace_product_images')
    op.drop_index(op.f('ix_marketplace_offers_marketplace_product_id'), table_name='marketplace_offers')
    op.drop_table('marketplace_offers')
    op.drop_index(op.f('ix_marketplace_internal_mappings_marketplace_provider'), table_name='marketplace_internal_mappings')
    op.drop_index(op.f('ix_marketplace_internal_mappings_marketplace_product_id'), table_name='marketplace_internal_mappings')
    op.drop_index(op.f('ix_marketplace_internal_mappings_internal_product_id'), table_name='marketplace_internal_mappings')
    op.drop_table('marketplace_internal_mappings')
    op.drop_index(op.f('ix_marketplace_finance_information_marketplace_product_id'), table_name='marketplace_finance_information')
    op.drop_table('marketplace_finance_information')
    op.drop_index(op.f('ix_marketplace_providers_code'), table_name='marketplace_providers')
    op.drop_table('marketplace_providers')
    op.drop_index('ix_marketplace_provider_product', table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_provider_product_id'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_provider'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_category'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_brand'), table_name='marketplace_products')
    op.drop_table('marketplace_products')
    op.drop_index(op.f('ix_marketplace_fetch_logs_provider'), table_name='marketplace_fetch_logs')
    op.drop_index(op.f('ix_marketplace_fetch_logs_correlation_id'), table_name='marketplace_fetch_logs')
    op.drop_table('marketplace_fetch_logs')
    # ### end Alembic commands ###
